version: "3.7"

services:

    api:
        build: ./api
        container_name: api
        restart: always
        environment:
            - APP_NAME= BackEndApp
        expose:
            - 8080

    client:
        build: ./client
        container_name: client
        restart: always
        environment:
            - APP_NAME= FrontEndApp
        expose:
            - 6060
        links:
            - api
    
    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - "9080:80"